/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const BadgeAwardResult = IDL.Record({
  'unlockedAt' : Timestamp,
  'alreadyHad' : IDL.Bool,
  'badgeId' : IDL.Text,
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const AwardXPArgs = IDL.Record({
  'userId' : UserId,
  'difficulty' : Difficulty,
  'accuracy' : IDL.Float64,
});
export const Level = IDL.Variant({
  'Beginner' : IDL.Null,
  'Scholar' : IDL.Null,
  'Amateur' : IDL.Null,
  'Topper' : IDL.Null,
  'Expert' : IDL.Null,
});
export const XPAwardResult = IDL.Record({
  'xpAwarded' : IDL.Nat,
  'newTotalXP' : IDL.Nat,
  'leveledUp' : IDL.Bool,
  'newLevel' : Level,
});
export const StreakInfo = IDL.Record({
  'isTodayCompleted' : IDL.Bool,
  'lastCompletedDate' : IDL.Opt(IDL.Text),
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'currentXP' : IDL.Nat,
  'userId' : UserId,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'level' : Level,
  'avatarUrl' : IDL.Text,
});
export const Subject = IDL.Variant({
  'Accounts' : IDL.Null,
  'GeneralTest' : IDL.Null,
  'Maths' : IDL.Null,
  'English' : IDL.Null,
  'BusinessStudies' : IDL.Null,
});
export const SectionBreakdown = IDL.Record({
  'total' : IDL.Nat,
  'subject' : Subject,
  'score' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const MockTestResult = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'testName' : IDL.Text,
  'score' : IDL.Nat,
  'sectionBreakdown' : IDL.Vec(SectionBreakdown),
  'totalQuestions' : IDL.Nat,
  'timestamp' : Timestamp,
  'timeTaken' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const Badge = IDL.Record({ 'id' : IDL.Text, 'unlockedAt' : Timestamp });
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'joinDate' : Timestamp,
  'currentXP' : IDL.Nat,
  'name' : IDL.Text,
  'badges' : IDL.Vec(Badge),
  'email' : IDL.Text,
  'level' : Level,
  'lastStudyDate' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Text,
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'subject' : Subject,
  'userId' : UserId,
  'difficulty' : Difficulty,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Timestamp,
  'timeTaken' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const RegisterUserArgs = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const SaveMockTestResultArgs = IDL.Record({
  'testName' : IDL.Text,
  'score' : IDL.Nat,
  'sectionBreakdown' : IDL.Vec(SectionBreakdown),
  'totalQuestions' : IDL.Nat,
  'timeTaken' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const SaveQuizResultArgs = IDL.Record({
  'subject' : Subject,
  'difficulty' : Difficulty,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timeTaken' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const UpdateUserArgs = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'awardBadge' : IDL.Func([UserId, IDL.Text], [IDL.Opt(BadgeAwardResult)], []),
  'awardXP' : IDL.Func([AwardXPArgs], [IDL.Opt(XPAwardResult)], []),
  'calculateLevel' : IDL.Func([IDL.Nat], [Level], ['query']),
  'completeDailyChallenge' : IDL.Func([], [IDL.Opt(StreakInfo)], []),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyMockTestHistory' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getMyQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getStreakInfo' : IDL.Func([], [IDL.Opt(StreakInfo)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
  'isTodayChallengeCompleted' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([RegisterUserArgs], [UserProfilePublic], []),
  'saveMockTestResult' : IDL.Func(
      [SaveMockTestResultArgs],
      [MockTestResult],
      [],
    ),
  'saveQuizResult' : IDL.Func([SaveQuizResultArgs], [QuizResult], []),
  'updateUser' : IDL.Func([UpdateUserArgs], [IDL.Opt(UserProfilePublic)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const BadgeAwardResult = IDL.Record({
    'unlockedAt' : Timestamp,
    'alreadyHad' : IDL.Bool,
    'badgeId' : IDL.Text,
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const AwardXPArgs = IDL.Record({
    'userId' : UserId,
    'difficulty' : Difficulty,
    'accuracy' : IDL.Float64,
  });
  const Level = IDL.Variant({
    'Beginner' : IDL.Null,
    'Scholar' : IDL.Null,
    'Amateur' : IDL.Null,
    'Topper' : IDL.Null,
    'Expert' : IDL.Null,
  });
  const XPAwardResult = IDL.Record({
    'xpAwarded' : IDL.Nat,
    'newTotalXP' : IDL.Nat,
    'leveledUp' : IDL.Bool,
    'newLevel' : Level,
  });
  const StreakInfo = IDL.Record({
    'isTodayCompleted' : IDL.Bool,
    'lastCompletedDate' : IDL.Opt(IDL.Text),
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'currentXP' : IDL.Nat,
    'userId' : UserId,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'level' : Level,
    'avatarUrl' : IDL.Text,
  });
  const Subject = IDL.Variant({
    'Accounts' : IDL.Null,
    'GeneralTest' : IDL.Null,
    'Maths' : IDL.Null,
    'English' : IDL.Null,
    'BusinessStudies' : IDL.Null,
  });
  const SectionBreakdown = IDL.Record({
    'total' : IDL.Nat,
    'subject' : Subject,
    'score' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const MockTestResult = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'testName' : IDL.Text,
    'score' : IDL.Nat,
    'sectionBreakdown' : IDL.Vec(SectionBreakdown),
    'totalQuestions' : IDL.Nat,
    'timestamp' : Timestamp,
    'timeTaken' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const Badge = IDL.Record({ 'id' : IDL.Text, 'unlockedAt' : Timestamp });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'joinDate' : Timestamp,
    'currentXP' : IDL.Nat,
    'name' : IDL.Text,
    'badges' : IDL.Vec(Badge),
    'email' : IDL.Text,
    'level' : Level,
    'lastStudyDate' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Text,
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'subject' : Subject,
    'userId' : UserId,
    'difficulty' : Difficulty,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Timestamp,
    'timeTaken' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const RegisterUserArgs = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const SaveMockTestResultArgs = IDL.Record({
    'testName' : IDL.Text,
    'score' : IDL.Nat,
    'sectionBreakdown' : IDL.Vec(SectionBreakdown),
    'totalQuestions' : IDL.Nat,
    'timeTaken' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const SaveQuizResultArgs = IDL.Record({
    'subject' : Subject,
    'difficulty' : Difficulty,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timeTaken' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const UpdateUserArgs = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'awardBadge' : IDL.Func(
        [UserId, IDL.Text],
        [IDL.Opt(BadgeAwardResult)],
        [],
      ),
    'awardXP' : IDL.Func([AwardXPArgs], [IDL.Opt(XPAwardResult)], []),
    'calculateLevel' : IDL.Func([IDL.Nat], [Level], ['query']),
    'completeDailyChallenge' : IDL.Func([], [IDL.Opt(StreakInfo)], []),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyMockTestHistory' : IDL.Func([], [IDL.Vec(MockTestResult)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getMyQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getStreakInfo' : IDL.Func([], [IDL.Opt(StreakInfo)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
    'isTodayChallengeCompleted' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([RegisterUserArgs], [UserProfilePublic], []),
    'saveMockTestResult' : IDL.Func(
        [SaveMockTestResultArgs],
        [MockTestResult],
        [],
      ),
    'saveQuizResult' : IDL.Func([SaveQuizResultArgs], [QuizResult], []),
    'updateUser' : IDL.Func([UpdateUserArgs], [IDL.Opt(UserProfilePublic)], []),
  });
};

export const init = ({ IDL }) => { return []; };