/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AwardXPArgs {
  'userId' : UserId,
  'difficulty' : Difficulty,
  'accuracy' : number,
}
export interface Badge { 'id' : string, 'unlockedAt' : Timestamp }
export interface BadgeAwardResult {
  'unlockedAt' : Timestamp,
  'alreadyHad' : boolean,
  'badgeId' : string,
}
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface LeaderboardEntry {
  'currentXP' : bigint,
  'userId' : UserId,
  'name' : string,
  'rank' : bigint,
  'level' : Level,
  'avatarUrl' : string,
}
export type Level = { 'Beginner' : null } |
  { 'Scholar' : null } |
  { 'Amateur' : null } |
  { 'Topper' : null } |
  { 'Expert' : null };
export interface MockTestResult {
  'id' : bigint,
  'userId' : UserId,
  'testName' : string,
  'score' : bigint,
  'sectionBreakdown' : Array<SectionBreakdown>,
  'totalQuestions' : bigint,
  'timestamp' : Timestamp,
  'timeTaken' : bigint,
  'accuracy' : number,
}
export interface QuizResult {
  'id' : bigint,
  'subject' : Subject,
  'userId' : UserId,
  'difficulty' : Difficulty,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Timestamp,
  'timeTaken' : bigint,
  'accuracy' : number,
}
export interface RegisterUserArgs {
  'name' : string,
  'email' : string,
  'avatarUrl' : string,
}
export interface SaveMockTestResultArgs {
  'testName' : string,
  'score' : bigint,
  'sectionBreakdown' : Array<SectionBreakdown>,
  'totalQuestions' : bigint,
  'timeTaken' : bigint,
  'accuracy' : number,
}
export interface SaveQuizResultArgs {
  'subject' : Subject,
  'difficulty' : Difficulty,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timeTaken' : bigint,
  'accuracy' : number,
}
export interface SectionBreakdown {
  'total' : bigint,
  'subject' : Subject,
  'score' : bigint,
  'accuracy' : number,
}
export interface StreakInfo {
  'isTodayCompleted' : boolean,
  'lastCompletedDate' : [] | [string],
  'bestStreak' : bigint,
  'currentStreak' : bigint,
}
export type Subject = { 'Accounts' : null } |
  { 'GeneralTest' : null } |
  { 'Maths' : null } |
  { 'English' : null } |
  { 'BusinessStudies' : null };
export type Timestamp = bigint;
export interface UpdateUserArgs {
  'name' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'joinDate' : Timestamp,
  'currentXP' : bigint,
  'name' : string,
  'badges' : Array<Badge>,
  'email' : string,
  'level' : Level,
  'lastStudyDate' : [] | [string],
  'avatarUrl' : string,
  'bestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface XPAwardResult {
  'xpAwarded' : bigint,
  'newTotalXP' : bigint,
  'leveledUp' : boolean,
  'newLevel' : Level,
}
export interface _SERVICE {
  'awardBadge' : ActorMethod<[UserId, string], [] | [BadgeAwardResult]>,
  'awardXP' : ActorMethod<[AwardXPArgs], [] | [XPAwardResult]>,
  'calculateLevel' : ActorMethod<[bigint], Level>,
  'completeDailyChallenge' : ActorMethod<[], [] | [StreakInfo]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyMockTestHistory' : ActorMethod<[], Array<MockTestResult>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyQuizHistory' : ActorMethod<[], Array<QuizResult>>,
  'getStreakInfo' : ActorMethod<[], [] | [StreakInfo]>,
  'getUser' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'isTodayChallengeCompleted' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[RegisterUserArgs], UserProfilePublic>,
  'saveMockTestResult' : ActorMethod<[SaveMockTestResultArgs], MockTestResult>,
  'saveQuizResult' : ActorMethod<[SaveQuizResultArgs], QuizResult>,
  'updateUser' : ActorMethod<[UpdateUserArgs], [] | [UserProfilePublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];