/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AwardXPArgs {
    userId: UserId;
    difficulty: Difficulty;
    accuracy: number;
}
export interface LeaderboardEntry {
    currentXP: bigint;
    userId: UserId;
    name: string;
    rank: bigint;
    level: Level;
    avatarUrl: string;
}
export type Timestamp = bigint;
export interface StreakInfo {
    isTodayCompleted: boolean;
    lastCompletedDate?: string;
    bestStreak: bigint;
    currentStreak: bigint;
}
export interface RegisterUserArgs {
    name: string;
    email: string;
    avatarUrl: string;
}
export interface MockTestResult {
    id: bigint;
    userId: UserId;
    testName: string;
    score: bigint;
    sectionBreakdown: Array<SectionBreakdown>;
    totalQuestions: bigint;
    timestamp: Timestamp;
    timeTaken: bigint;
    accuracy: number;
}
export interface SaveQuizResultArgs {
    subject: Subject;
    difficulty: Difficulty;
    score: bigint;
    totalQuestions: bigint;
    timeTaken: bigint;
    accuracy: number;
}
export interface QuizResult {
    id: bigint;
    subject: Subject;
    userId: UserId;
    difficulty: Difficulty;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Timestamp;
    timeTaken: bigint;
    accuracy: number;
}
export interface UserProfilePublic {
    id: UserId;
    joinDate: Timestamp;
    currentXP: bigint;
    name: string;
    badges: Array<Badge>;
    email: string;
    level: Level;
    lastStudyDate?: string;
    avatarUrl: string;
    bestStreak: bigint;
    currentStreak: bigint;
}
export interface XPAwardResult {
    xpAwarded: bigint;
    newTotalXP: bigint;
    leveledUp: boolean;
    newLevel: Level;
}
export interface Badge {
    id: string;
    unlockedAt: Timestamp;
}
export type UserId = Principal;
export interface BadgeAwardResult {
    unlockedAt: Timestamp;
    alreadyHad: boolean;
    badgeId: string;
}
export interface SectionBreakdown {
    total: bigint;
    subject: Subject;
    score: bigint;
    accuracy: number;
}
export interface SaveMockTestResultArgs {
    testName: string;
    score: bigint;
    sectionBreakdown: Array<SectionBreakdown>;
    totalQuestions: bigint;
    timeTaken: bigint;
    accuracy: number;
}
export interface UpdateUserArgs {
    name: string;
    email: string;
    avatarUrl: string;
}
export enum Difficulty {
    Easy = "Easy",
    Hard = "Hard",
    Medium = "Medium"
}
export enum Level {
    Beginner = "Beginner",
    Scholar = "Scholar",
    Amateur = "Amateur",
    Topper = "Topper",
    Expert = "Expert"
}
export enum Subject {
    Accounts = "Accounts",
    GeneralTest = "GeneralTest",
    Maths = "Maths",
    English = "English",
    BusinessStudies = "BusinessStudies"
}
export interface backendInterface {
    awardBadge(userId: UserId, badgeId: string): Promise<BadgeAwardResult | null>;
    awardXP(args: AwardXPArgs): Promise<XPAwardResult | null>;
    calculateLevel(xp: bigint): Promise<Level>;
    completeDailyChallenge(): Promise<StreakInfo | null>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyMockTestHistory(): Promise<Array<MockTestResult>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyQuizHistory(): Promise<Array<QuizResult>>;
    getStreakInfo(): Promise<StreakInfo | null>;
    getUser(userId: UserId): Promise<UserProfilePublic | null>;
    isTodayChallengeCompleted(): Promise<boolean>;
    registerUser(args: RegisterUserArgs): Promise<UserProfilePublic>;
    saveMockTestResult(args: SaveMockTestResultArgs): Promise<MockTestResult>;
    saveQuizResult(args: SaveQuizResultArgs): Promise<QuizResult>;
    updateUser(args: UpdateUserArgs): Promise<UserProfilePublic | null>;
}
import type { AwardXPArgs as _AwardXPArgs, Badge as _Badge, BadgeAwardResult as _BadgeAwardResult, Difficulty as _Difficulty, LeaderboardEntry as _LeaderboardEntry, Level as _Level, MockTestResult as _MockTestResult, QuizResult as _QuizResult, SaveMockTestResultArgs as _SaveMockTestResultArgs, SaveQuizResultArgs as _SaveQuizResultArgs, SectionBreakdown as _SectionBreakdown, StreakInfo as _StreakInfo, Subject as _Subject, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic, XPAwardResult as _XPAwardResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async awardBadge(arg0: UserId, arg1: string): Promise<BadgeAwardResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async awardXP(arg0: AwardXPArgs): Promise<XPAwardResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.awardXP(to_candid_AwardXPArgs_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardXP(to_candid_AwardXPArgs_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateLevel(arg0: bigint): Promise<Level> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateLevel(arg0);
                return from_candid_Level_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateLevel(arg0);
            return from_candid_Level_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeDailyChallenge(): Promise<StreakInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeDailyChallenge();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeDailyChallenge();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMockTestHistory(): Promise<Array<MockTestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMockTestHistory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMockTestHistory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuizHistory(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizHistory();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizHistory();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreakInfo(): Promise<StreakInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakInfo();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakInfo();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isTodayChallengeCompleted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTodayChallengeCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTodayChallengeCompleted();
            return result;
        }
    }
    async registerUser(arg0: RegisterUserArgs): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_UserProfilePublic_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_UserProfilePublic_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMockTestResult(arg0: SaveMockTestResultArgs): Promise<MockTestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMockTestResult(to_candid_SaveMockTestResultArgs_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MockTestResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMockTestResult(to_candid_SaveMockTestResultArgs_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MockTestResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveQuizResult(arg0: SaveQuizResultArgs): Promise<QuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResult(to_candid_SaveQuizResultArgs_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_QuizResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResult(to_candid_SaveQuizResultArgs_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_QuizResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UpdateUserArgs): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Difficulty_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Level_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MockTestResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockTestResult): MockTestResult {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_QuizResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizResult): QuizResult {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SectionBreakdown_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionBreakdown): SectionBreakdown {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_StreakInfo_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreakInfo): StreakInfo {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_XPAwardResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _XPAwardResult): XPAwardResult {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BadgeAwardResult]): BadgeAwardResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StreakInfo]): StreakInfo | null {
    return value.length === 0 ? null : from_candid_StreakInfo_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_XPAwardResult]): XPAwardResult | null {
    return value.length === 0 ? null : from_candid_XPAwardResult_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isTodayCompleted: boolean;
    lastCompletedDate: [] | [string];
    bestStreak: bigint;
    currentStreak: bigint;
}): {
    isTodayCompleted: boolean;
    lastCompletedDate?: string;
    bestStreak: bigint;
    currentStreak: bigint;
} {
    return {
        isTodayCompleted: value.isTodayCompleted,
        lastCompletedDate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastCompletedDate)),
        bestStreak: value.bestStreak,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentXP: bigint;
    userId: _UserId;
    name: string;
    rank: bigint;
    level: _Level;
    avatarUrl: string;
}): {
    currentXP: bigint;
    userId: UserId;
    name: string;
    rank: bigint;
    level: Level;
    avatarUrl: string;
} {
    return {
        currentXP: value.currentXP,
        userId: value.userId,
        name: value.name,
        rank: value.rank,
        level: from_candid_Level_n9(_uploadFile, _downloadFile, value.level),
        avatarUrl: value.avatarUrl
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    testName: string;
    score: bigint;
    sectionBreakdown: Array<_SectionBreakdown>;
    totalQuestions: bigint;
    timestamp: _Timestamp;
    timeTaken: bigint;
    accuracy: number;
}): {
    id: bigint;
    userId: UserId;
    testName: string;
    score: bigint;
    sectionBreakdown: Array<SectionBreakdown>;
    totalQuestions: bigint;
    timestamp: Timestamp;
    timeTaken: bigint;
    accuracy: number;
} {
    return {
        id: value.id,
        userId: value.userId,
        testName: value.testName,
        score: value.score,
        sectionBreakdown: from_candid_vec_n21(_uploadFile, _downloadFile, value.sectionBreakdown),
        totalQuestions: value.totalQuestions,
        timestamp: value.timestamp,
        timeTaken: value.timeTaken,
        accuracy: value.accuracy
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    subject: _Subject;
    score: bigint;
    accuracy: number;
}): {
    total: bigint;
    subject: Subject;
    score: bigint;
    accuracy: number;
} {
    return {
        total: value.total,
        subject: from_candid_Subject_n24(_uploadFile, _downloadFile, value.subject),
        score: value.score,
        accuracy: value.accuracy
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    joinDate: _Timestamp;
    currentXP: bigint;
    name: string;
    badges: Array<_Badge>;
    email: string;
    level: _Level;
    lastStudyDate: [] | [string];
    avatarUrl: string;
    bestStreak: bigint;
    currentStreak: bigint;
}): {
    id: UserId;
    joinDate: Timestamp;
    currentXP: bigint;
    name: string;
    badges: Array<Badge>;
    email: string;
    level: Level;
    lastStudyDate?: string;
    avatarUrl: string;
    bestStreak: bigint;
    currentStreak: bigint;
} {
    return {
        id: value.id,
        joinDate: value.joinDate,
        currentXP: value.currentXP,
        name: value.name,
        badges: value.badges,
        email: value.email,
        level: from_candid_Level_n9(_uploadFile, _downloadFile, value.level),
        lastStudyDate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastStudyDate)),
        avatarUrl: value.avatarUrl,
        bestStreak: value.bestStreak,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subject: _Subject;
    userId: _UserId;
    difficulty: _Difficulty;
    score: bigint;
    totalQuestions: bigint;
    timestamp: _Timestamp;
    timeTaken: bigint;
    accuracy: number;
}): {
    id: bigint;
    subject: Subject;
    userId: UserId;
    difficulty: Difficulty;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Timestamp;
    timeTaken: bigint;
    accuracy: number;
} {
    return {
        id: value.id,
        subject: from_candid_Subject_n24(_uploadFile, _downloadFile, value.subject),
        userId: value.userId,
        difficulty: from_candid_Difficulty_n32(_uploadFile, _downloadFile, value.difficulty),
        score: value.score,
        totalQuestions: value.totalQuestions,
        timestamp: value.timestamp,
        timeTaken: value.timeTaken,
        accuracy: value.accuracy
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xpAwarded: bigint;
    newTotalXP: bigint;
    leveledUp: boolean;
    newLevel: _Level;
}): {
    xpAwarded: bigint;
    newTotalXP: bigint;
    leveledUp: boolean;
    newLevel: Level;
} {
    return {
        xpAwarded: value.xpAwarded,
        newTotalXP: value.newTotalXP,
        leveledUp: value.leveledUp,
        newLevel: from_candid_Level_n9(_uploadFile, _downloadFile, value.newLevel)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Scholar: null;
} | {
    Amateur: null;
} | {
    Topper: null;
} | {
    Expert: null;
}): Level {
    return "Beginner" in value ? Level.Beginner : "Scholar" in value ? Level.Scholar : "Amateur" in value ? Level.Amateur : "Topper" in value ? Level.Topper : "Expert" in value ? Level.Expert : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Accounts: null;
} | {
    GeneralTest: null;
} | {
    Maths: null;
} | {
    English: null;
} | {
    BusinessStudies: null;
}): Subject {
    return "Accounts" in value ? Subject.Accounts : "GeneralTest" in value ? Subject.GeneralTest : "Maths" in value ? Subject.Maths : "English" in value ? Subject.English : "BusinessStudies" in value ? Subject.BusinessStudies : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "Hard" in value ? Difficulty.Hard : "Medium" in value ? Difficulty.Medium : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MockTestResult>): Array<MockTestResult> {
    return value.map((x)=>from_candid_MockTestResult_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SectionBreakdown>): Array<SectionBreakdown> {
    return value.map((x)=>from_candid_SectionBreakdown_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizResult>): Array<QuizResult> {
    return value.map((x)=>from_candid_QuizResult_n30(_uploadFile, _downloadFile, x));
}
function to_candid_AwardXPArgs_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AwardXPArgs): _AwardXPArgs {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_SaveMockTestResultArgs_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveMockTestResultArgs): _SaveMockTestResultArgs {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_SaveQuizResultArgs_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveQuizResultArgs): _SaveQuizResultArgs {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_SectionBreakdown_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionBreakdown): _SectionBreakdown {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: UserId;
    difficulty: Difficulty;
    accuracy: number;
}): {
    userId: _UserId;
    difficulty: _Difficulty;
    accuracy: number;
} {
    return {
        userId: value.userId,
        difficulty: to_candid_Difficulty_n4(_uploadFile, _downloadFile, value.difficulty),
        accuracy: value.accuracy
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    testName: string;
    score: bigint;
    sectionBreakdown: Array<SectionBreakdown>;
    totalQuestions: bigint;
    timeTaken: bigint;
    accuracy: number;
}): {
    testName: string;
    score: bigint;
    sectionBreakdown: Array<_SectionBreakdown>;
    totalQuestions: bigint;
    timeTaken: bigint;
    accuracy: number;
} {
    return {
        testName: value.testName,
        score: value.score,
        sectionBreakdown: to_candid_vec_n36(_uploadFile, _downloadFile, value.sectionBreakdown),
        totalQuestions: value.totalQuestions,
        timeTaken: value.timeTaken,
        accuracy: value.accuracy
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    subject: Subject;
    score: bigint;
    accuracy: number;
}): {
    total: bigint;
    subject: _Subject;
    score: bigint;
    accuracy: number;
} {
    return {
        total: value.total,
        subject: to_candid_Subject_n39(_uploadFile, _downloadFile, value.subject),
        score: value.score,
        accuracy: value.accuracy
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: Subject;
    difficulty: Difficulty;
    score: bigint;
    totalQuestions: bigint;
    timeTaken: bigint;
    accuracy: number;
}): {
    subject: _Subject;
    difficulty: _Difficulty;
    score: bigint;
    totalQuestions: bigint;
    timeTaken: bigint;
    accuracy: number;
} {
    return {
        subject: to_candid_Subject_n39(_uploadFile, _downloadFile, value.subject),
        difficulty: to_candid_Difficulty_n4(_uploadFile, _downloadFile, value.difficulty),
        score: value.score,
        totalQuestions: value.totalQuestions,
        timeTaken: value.timeTaken,
        accuracy: value.accuracy
    };
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    Accounts: null;
} | {
    GeneralTest: null;
} | {
    Maths: null;
} | {
    English: null;
} | {
    BusinessStudies: null;
} {
    return value == Subject.Accounts ? {
        Accounts: null
    } : value == Subject.GeneralTest ? {
        GeneralTest: null
    } : value == Subject.Maths ? {
        Maths: null
    } : value == Subject.English ? {
        English: null
    } : value == Subject.BusinessStudies ? {
        BusinessStudies: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
} {
    return value == Difficulty.Easy ? {
        Easy: null
    } : value == Difficulty.Hard ? {
        Hard: null
    } : value == Difficulty.Medium ? {
        Medium: null
    } : value;
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SectionBreakdown>): Array<_SectionBreakdown> {
    return value.map((x)=>to_candid_SectionBreakdown_n37(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
